// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTq1tIsCI-17jRaWMZRUCZFXFtiGB-z8',
    appId: '1:166152507893:android:d244b41fca4753ddda10bc',
    messagingSenderId: '166152507893',
    projectId: 'mad-final-project-home',
    storageBucket: 'mad-final-project-home.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7qbJp4jeFgXW8q3GY53Qc2Oba8X7ZJ0w',
    appId: '1:166152507893:ios:f285943183ed83d2da10bc',
    messagingSenderId: '166152507893',
    projectId: 'mad-final-project-home',
    storageBucket: 'mad-final-project-home.appspot.com',
    androidClientId: '166152507893-nbb38djdja1d646cb6n4hnvs6fe6qikn.apps.googleusercontent.com',
    iosClientId: '166152507893-3dm7sf3nt5cbidqe2491ijv7b1dpgf1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.madFinalProject',
  );
}
